# SITE CONFIGURATION
title: 휘진's Blog # your site title
author: Hweejin Lim (임휘진) # You :P
description: > # Meta description of Homepage
  업무&일상을 담는 공간
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hweejin-lim.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
# social:
#   name: Your Name
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Work', link: '/work'}
  - {name: 'Life', link: '/life'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  고민하고, 흔적을 글로 남기기
  

hero_img: posts/sleek.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: radiancej@gmail.com # email for form submission


# github_username:  hweejin-lim # replace with your_github_username or comment to remove link from footer
# facebook_username: radiancej@naver.com # replace with your_github_username or comment to remove link from footer
# instagram_username: imhwijin # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: 휘진's Blog # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
